# Generated by Django 5.2.7 on 2026-05-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Import prcie'),
        ),
    ]
