# Generated by Django 5.2.7 on 2026-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_discount_percent_alter_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date update'),
        ),
    ]
