# Generated by Django 5.2.7 on 2026-05-04 23:59

import tools.path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(blank=True)),
                ('image', models.ImageField(upload_to=tools.path.get_upload_path)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
        ),
    ]
