# Generated by Django 5.2.7 on 2026-05-05 11:58

import tools.path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_update_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=tools.path.get_upload_path),
        ),
    ]
